server:
  port: 2333

lavalink:
  server:
    password: "powerbysunjixxpass001"
    sources:
      youtube: true
      soundcloud: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    gc-warnings: true
