server:
  port: 2333

spring:
  main:
    banner-mode: "off"

lavalink:
  server:
    password: powerbysunjixxpass001
    sources:
      youtube: true
      soundcloud: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    enableTrace: false
